pipeline {
  //Donde se va a ejecutar el Pipeline
  agent {
    label 'Slave_Induccion'
  }

  //Opciones específicas de Pipeline dentro del Pipeline
  options {
    	buildDiscarder(logRotator(numToKeepStr: '3'))
 	disableConcurrentBuilds()
  }

  
	
  tools {
    jdk 'JDK8_Centos' //Preinstalada en la Configuración del Master
    gradle 'Gradle5.0_Centos' //Preinstalada en la Configuración del Master
  }	


  //Aquí comienzan los “items” del Pipeline
  stages{
    stage('Checkout') {
      steps{
        echo "------------>Checkout<------------"
		checkout([
			$class: 'GitSCM', 
			branches: [[name: '*/master']], 
			doGenerateSubmoduleConfigurations: false, 
			extensions: [], 
			gitTool: 'Default', 
			submoduleCfg: [], 
			userRemoteConfigs: [[
			credentialsId: 'GitHub_diego-cardona', 
			url:'https://github.com/diego-cardona/spa.git'
			]]
		])	
      }
    }
    
	
	gradle --b microservicio/build.gradle clean'
	
	
	
    stage('Build') {
      steps {
        echo "------------>Build<------------"
		//Construir sin tarea test que se ejecutó previamente
		sh 'gradle --b microservicio/build.gradle build'
      }
    }  
  }

}
